openapi: 3.0.3
info:
  title: Projeto de Controle de Filmes - SENAI Jandira
  description: |-
   API destinada a controle de filmes para o projeto "Bem Legal" do SENAI
  termsOfService: http://swagger.io/terms/
  contact:
    email: gustavovidalgva@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: http://
paths:
  # ENDPOINTS - PRODUTO
  /v1/frequency80cafe/produto:
    get:
      tags:
        - Produto
      summary: Lista todos os produtos
      description: Endpoint para listar todos os produtos cadastradss
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Produto'
        '404':
          description: Error Not Found
        '500':
          description: Error Internal Server (Controller | Model)
  /v1/frequency80cafe/produto/{id}:
    get:
      tags:
        - Produto
      summary: Busca um produto pelo id
      description: Endpoint para retornar um produto pelo id
      parameters:
        - name: id
          in: path
          description: id para realizar a busca do produto
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Produto'          
        '400':
          description: Error Bad Request (id)
        '404':
          description: Error Not found
        '500':
          description: Error Internal Server (Controller | Model)
components:
  schemas:
    # SCHEMAS GERAIS
    Produto:
      required:
        - id
        - nome
        - preco
        - descricao
        - status
      type: object
      properties:
        id:
          type: integer
        nome:
          type: string
          description: O número máximo de caracteres é de 40
        preco:
          type: number
          format: double
          example: 999.99
        descricao:
          type: string
        status:
          type: boolean
        imagem:
          type: array
          items:
            type: object
            properties:
              id:
                type: integer
              url:
                type: string
        categoria:
          type: array
          items:
            type: object
            properties:
              id:
                type: integer
              categoria:
                type: string


  requestBodies:
    Produto:
      description: Objeto que deve ser enviado no Body das requisicoes
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Produto'