openapi: 3.0.3
info:
  title: Projeto de Controle de Produtos (Landing Page) - Frequency 80 Cafe
  description: |-
    API destinada a controle de produtos para a cafeteria temática "Frequency 80 Cafe".
  termsOfService: http://swagger.io/terms/
  contact:
    email: gustavovidalgva@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: http://localhost:8080
tags:
  - name: "Administração (Admin)"
    description: "Endpoints restritos (admin) para gerenciamento do sistema"
  - name: "Administração (Categoria)"
    description: "Endpoints restritos (categoria) para gerenciamento do sistema"
  - name: "Administração (Imagem)"
    description: "Endpoints restritos (imagem) para gerenciamento do sistema"
  - name: "Administração (Produto)"
    description: "Endpoints restritos (produto) para gerenciamento do sistema"
  - name: "Landing Page (Categoria)"
    description: "Endpoints públicos (categoria) utilizados na página principal"
  - name: "Landing Page (Imagem)"
    description: "Endpoints públicos (imagem) utilizados na página principal"
  - name: "Landing Page (Produto)"
    description: "Endpoints públicos (produto) utilizados na página principal"
paths:
  # ENDPOINTS - CATEGORIA
  /v1/frequency80cafe/categoria:
    get:
      tags:
        - Landing Page (Categoria)
      summary: Lista todas as categorias
      description: Endpoint para listar todas as categorias cadastradas
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/CategoriaGet"
        "404":
          description: Error Not Found
        "500":
          description: Error Internal Server (Controller | Model)
  /v1/frequency80cafe/categoria/{id}:
    get:
      tags:
        - Landing Page (Categoria)
      summary: Busca uma categoria pelo id
      description: Endpoint para retornar uma categoria pelo id
      parameters:
        - name: id
          in: path
          description: id para realizar a busca da categoria
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CategoriaGet"
        "400":
          description: Error Bad Request (id)
        "404":
          description: Error Not Found
        "500":
          description: Error Internal Server (Controller | Model)
  # ENDPOINTS - IMAGEM
  /v1/frequency80cafe/imagem:
    get:
      tags:
        - Landing Page (Imagem)
      summary: Lista todas as imagens
      description: Endpoint para listar todas as imagens cadastradas
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ImagemGet"
        "404":
          description: Error Not Found
        "500":
          description: Error Internal Server (Controller | Model)
  /v1/frequency80cafe/imagem/{id}:
    get:
      tags:
        - Landing Page (Imagem)
      summary: Busca uma imagem pelo id
      description: Endpoint para retornar uma imagem pelo id
      parameters:
        - name: id
          in: path
          description: id para realizar a busca da imagem
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ImagemGet"
        "400":
          description: Error Bad Request (id)
        "404":
          description: Error Not Found
        "500":
          description: Error Internal Server (Controller | Model)
  # ENDPOINTS - PRODUTO
  /v1/frequency80cafe/produto:
    get:
      tags:
        - Landing Page (Produto)
      summary: Lista todos os produtos
      description: Endpoint para listar todos os produtos cadastrados
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ProdutoGet"
        "404":
          description: Error Not Found
        "500":
          description: Error Internal Server (Controller | Model)
  /v1/frequency80cafe/produto/{id}:
    get:
      tags:
        - Landing Page (Produto)
      summary: Busca um produto pelo id
      description: Endpoint para retornar um produto pelo id
      parameters:
        - name: id
          in: path
          description: id para realizar a busca do produto
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProdutoGet"
        "400":
          description: Error Bad Request (id)
        "404":
          description: Error Not Found
        "500":
          description: Error Internal Server (Controller | Model)
components:
  schemas:
    # SCHEMAS PARA OS GETS
    CategoriaGet:
      required:
        - id
      type: object
      properties:
        id:
          type: integer
          minimum: 1
        categoria:
          type: string
          maxLength: 45
    ImagemGet:
      required:
        - id
      type: object
      properties:
        id:
          type: integer
          minimum: 1
        url:
          type: string
          format: uri
          pattern: "^https?://.+"
          example: "https://imagem.example.com"
          maxLength: 255
    ProdutoGet:
      required:
        - id
      type: object
      properties:
        id:
          type: integer
          minimum: 1
        nome:
          type: string
          maxLength: 100
        descricao:
          type: string
        preco:
          type: number
          format: double
          minimum: 0
          maximum: 999.99
        imagem:
          type: array
          items:
            $ref: "#/components/schemas/ImagemGet"
        categoria:
          type: array
          items:
            $ref: "#/components/schemas/CategoriaGet"