openapi: 3.0.3
info:
  title: Projeto de Controle de Produtos (Landing Page) - Frequency 80 Cafe
  description: |-
    API destinada a controle de produtos para a cafeteria temática "Frequency 80 Cafe".
  termsOfService: http://swagger.io/terms/
  contact:
    email: gustavovidalgva@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: http://localhost:8080
paths:
  # ENDPOINTS - CATEGORIA
  /v1/frequency80cafe/landingpage/categoria:
    get:
      tags:
        - Categoria
      summary: Lista todas as categorias
      description: Endpoint para listar todas as categorias cadastradas
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/CategoriaGet"
        "404":
          description: Error Not Found
        "500":
          description: Error Internal Server (Controller | Model)
  /v1/frequency80cafe/landingpage/categoria/{id}:
    get:
      tags:
        - Categoria
      summary: Busca uma categoria pelo id
      description: Endpoint para retornar uma categoria pelo id
      parameters:
        - name: id
          in: path
          description: id para realizar a busca da categoria
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CategoriaGet"
        "400":
          description: Error Bad Request (id)
        "404":
          description: Error Not Found
        "500":
          description: Error Internal Server (Controller | Model)
  # ENDPOINTS - IMAGEM
  /v1/frequency80cafe/landingpage/imagem:
    get:
      tags:
        - Imagem
      summary: Lista todas as imagens
      description: Endpoint para listar todas as imagens cadastradas
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ImagemGet"
        "404":
          description: Error Not Found
        "500":
          description: Error Internal Server (Controller | Model)
  /v1/frequency80cafe/landingpage/imagem/{id}:
    get:
      tags:
        - Imagem
      summary: Busca uma imagem pelo id
      description: Endpoint para retornar uma imagem pelo id
      parameters:
        - name: id
          in: path
          description: id para realizar a busca da imagem
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ImagemGet"
        "400":
          description: Error Bad Request (id)
        "404":
          description: Error Not Found
        "500":
          description: Error Internal Server (Controller | Model)
  # ENDPOINTS - PRODUTO
  /v1/frequency80cafe/landingpage/produto:
    get:
      tags:
        - Produto
      summary: Lista todos os produtos
      description: Endpoint para listar todos os produtos cadastrados
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ProdutoGet"
        "404":
          description: Error Not Found
        "500":
          description: Error Internal Server (Controller | Model)
  /v1/frequency80cafe/landingpage/produto/{id}:
    get:
      tags:
        - Produto
      summary: Busca um produto pelo id
      description: Endpoint para retornar um produto pelo id
      parameters:
        - name: id
          in: path
          description: id para realizar a busca do produto
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProdutoGet"
        "400":
          description: Error Bad Request (id)
        "404":
          description: Error Not Found
        "500":
          description: Error Internal Server (Controller | Model)
components:
  schemas:
    # SCHEMAS PARA OS GETS
    CategoriaGet:
      required:
        - id
      type: object
      properties:
        id:
          type: integer
          minimum: 1
        categoria:
          type: string
          description: O número máximo de caracteres é de 45
          maxLength: 45
    ImagemGet:
      required:
        - id
      type: object
      properties:
        id:
          type: integer
          minimum: 1
        url:
          type: string
          format: uri
          pattern: "^https?://.+"
          example: "https://imagem.example.com"
          description: O número máximo de caracteres é de 255
          maxLength: 255
        produto: 
          type: object
          properties:
            id:
              type: integer
              minimum: 1
            nome:
              type: string
              maxLength: 100
            descricao:
              type: string
            preco:
              type: number
              format: double
              minimum: 0.99
              maximum: 999.99
    ProdutoGet:
      required:
        - id
      type: object
      properties:
        id:
          type: integer
          minimum: 1
        nome:
          type: string
          description: O número máximo de caracteres é de 100
          maxLength: 100
        descricao:
          type: string
          description: O número máximo de caracteres é ilimitado
        preco:
          type: number
          format: double
          minimum: 0
          maximum: 999.99
        imagem:
          type: array
          items:
            $ref: "#/components/schemas/ImagemGet"
        categoria:
          type: array
          items:
            $ref: "#/components/schemas/CategoriaGet"